name: autotrader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - fredapi
  - requests
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - statsmodels
  - pymc
  - matplotlib
  - seaborn
  - flask
  - jupyter
  - pytest
  - tqdm
  - black
  - pip:
    - alpaca_trade_api  
